version: '3.7'
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/backend
  #   depends_on:
  #     - db
  #   environment:
  #     SQLALCHEMY_DATABASE_URL: "postgres://postgres:test@db/postgres"
  #   networks:
  #     - proxynet
  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: 
  #   networks:
  #     - proxynet
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      CMC_PRO_API_KEY: ${CMC_PRO_API_KEY}
    volumes:
      - ./frontend:/app
    networks:
      - proxynet
networks:
  proxynet:
    name: custom_network