version: '3.7'
services:
  producer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
        - ./backend/producer/:/usr/src/app
    ports:
        - 8002:8000
    depends_on:
      - cryptodb
    #   - kafka
    environment:
      PYTHONUNBUFFERED: 1
      # SQLALCHEMY_DATABASE_URL: "postgres://postgres:test@db/postgres"
    networks:
      - proxynet
  cryptodb:
    image: postgres:13
    ports:
      - "5432:5432"
    environment: 
        POSTGRES_USER: devUser
        POSTGRES_PASSWORD: devUser1
        POSTGRES_DB: cryptos 
    networks:
      - proxynet  
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
  #     KAFKA_CREATE_TOPICS: "binancecryptostream"
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #     PORT: ${PORT}
  #     NODE_ENV: ${NODE_ENV}
  #     REACT_APP_BASE_URL: "https://api.binance.com/api/v3"
  #     CMC_PRO_API_KEY: ${CMC_PRO_API_KEY}
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - proxynet
networks:
  proxynet:
    name: custom_network